In [81]:
%pip install numpy pandas matplotlib scikit-learn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Requirement already satisfied: numpy in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (2.4.4)
Requirement already satisfied: pandas in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (3.0.2)
Requirement already satisfied: matplotlib in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (3.10.8)
Requirement already satisfied: scikit-learn in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\asus\appdata\roaming\python\python313\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [82]:
url = "https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/refs/heads/master/data/Telco-Customer-Churn.csv"
df=pd.read_csv(url)
pd.set_option("display.max_columns",None)

In [83]:
df.head(2)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No

In [84]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [85]:
df.shape

(7043, 21)

In [86]:
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [87]:
df.duplicated().sum()

np.int64(0)

In [88]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [89]:
df.describe(include='O')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_26840\2537740217.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='O')

,customerID,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges,Churn
count,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043
unique,7043,2,2,2,2,3,3,3,3,3,3,3,3,3,2,4,6531,2
top,7590-VHVEG,Male,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,20.2,No
freq,1,3555,3641,4933,6361,3390,3096,3498,3088,3095,3473,2810,2785,3875,4171,2365,11,5174

In [90]:
df['Churn']=df['Churn'].map({'Yes':1,'No':0})

In [91]:
df['gender']=df['gender'].map({'Female':1,'Male':0})

In [92]:
df['TotalCharges']=pd.to_numeric(df['TotalCharges'],errors='coerce')
df['TotalCharges'].fillna(df['TotalCharges'].median(), inplace=True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_26840\1570346737.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['TotalCharges'].fillna(df['TotalCharges'].median(), inplace=True)

0         29.85
1       1889.50
2        108.15
3       1840.75
4        151.65
         ...
7038    1990.50
7039    7362.90
7040     346.45
7041     306.60
7042    6844.50
Name: TotalCharges, Length: 7043, dtype: float64

In [93]:
df['StreamingMovies'].value_counts()

StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

In [94]:
df.drop(columns='customerID',inplace=True)

In [95]:
df['PaperlessBilling']=df['PaperlessBilling'].map({ ' Yes':1, "No":0})

In [96]:
df['StreamingMovies']=df['StreamingMovies'].map({'Yes':1,'No':0,'No internet service':-1})

In [97]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [98]:
numerical_cols=['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges']
for i in numerical_cols:
         if df[i].dtype=="string":
          df[i]=pd.factorize(df[i])[0]

In [99]:
numerical_cols=[f for f in numerical_cols if f in df.columns]

In [100]:
df.dropna(inplace=True)
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
1,0,0,1,0,34,1,1,0,1,1,1,0,0,0,1,0.0,1,56.95,1889.50,0
3,0,0,1,0,45,0,0,0,1,1,1,1,0,0,1,0.0,2,42.30,1840.75,0
7,1,0,1,0,10,0,0,0,1,1,0,0,0,0,0,0.0,1,29.75,301.90,0
9,0,0,1,1,62,1,1,0,1,0,0,0,0,0,1,0.0,2,56.15,3487.95,0
11,0,0,1,0,16,1,1,2,2,2,2,2,2,-1,2,0.0,3,18.95,326.80,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7019,1,0,1,0,39,1,1,2,2,2,2,2,2,-1,2,0.0,1,20.15,826.00,0
7027,0,0,1,0,13,1,1,0,0,0,0,1,1,1,0,0.0,1,73.35,931.55,0
7028,1,0,0,0,68,1,1,0,0,0,0,1,1,0,2,0.0,2,64.10,4326.25,0
7031,0,1,0,0,55,1,2,0,1,0,0,0,0,0,1,0.0,3,60.00,3316.10,0
7036,1,0,1,0,12,0,0,0,0,0,1,1,1,1,1,0.0,0,60.65,743.30,0

In [101]:
from sklearn.model_selection import train_test_split
X = df[numerical_cols]
y = df['Churn']

#stratify=y
X_train_1, X_test, y_train_1, y_test = train_test_split(X,y,
                                                    test_size=0.20,
                                                    stratify=y)

In [102]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train_1)
X_test=scaler.transform(X_test)
print("Max value in X_train:", np.max(X_train))

Max value in X_train: 3.369543564318636

In [103]:
x_train,x_val,y_train,y_val=train_test_split(X_train_1,y_train_1,test_size=0.2,random_state=42)

In [104]:
get_ipython().system('pip install Optuna')

Requirement already satisfied: Optuna in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (4.8.0)
Requirement already satisfied: alembic>=1.5.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from Optuna) (1.18.4)
Requirement already satisfied: colorlog in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from Optuna) (6.10.1)
Requirement already satisfied: numpy in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from Optuna) (2.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\asus\appdata\roaming\python\python313\site-packages (from Optuna) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from Optuna) (2.0.48)
Requirement already satisfied: tqdm in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from Optuna) (4.67.3)
Requirement already satisfied: PyYAML in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from Optuna) (6.0.3)
Requirement already satisfied: Mako in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from alembic>=1.5.0->Optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from alembic>=1.5.0->Optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy>=1.4.2->Optuna) (3.3.2)
Requirement already satisfied: colorama in c:\users\asus\appdata\roaming\python\python313\site-packages (from colorlog->Optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from Mako->alembic>=1.5.0->Optuna) (3.0.3)

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [105]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
import optuna

In [106]:
from sklearn.feature_selection import RFE

In [107]:

def obj(k):
  n=k.suggest_int('n_estimators',100,500)
  max_depth=k.suggest_int("max_depth",5,50)
  model=RandomForestClassifier(n_estimators=n, max_depth=max_depth)
  rfe=RFE(estimator=model,n_features_to_select=10)
  rfe.fit(X_train_1,y_train_1)
  return rfe.score(x_val,y_val)
study=optuna.create_study(direction="maximize")
study.optimize(obj,n_trials=10)

[I 2026-04-02 02:37:23,187] A new study created in memory with name: no-name-6525215f-29bd-4029-b4fc-d195edd10807
[I 2026-04-02 02:37:28,853] Trial 0 finished with value: 0.9934640522875817 and parameters: {'n_estimators': 169, 'max_depth': 26}. Best is trial 0 with value: 0.9934640522875817.
[I 2026-04-02 02:37:36,001] Trial 1 finished with value: 0.9934640522875817 and parameters: {'n_estimators': 321, 'max_depth': 24}. Best is trial 0 with value: 0.9934640522875817.
[I 2026-04-02 02:37:40,177] Trial 2 finished with value: 0.9934640522875817 and parameters: {'n_estimators': 150, 'max_depth': 45}. Best is trial 0 with value: 0.9934640522875817.
[I 2026-04-02 02:37:46,967] Trial 3 finished with value: 0.9934640522875817 and parameters: {'n_estimators': 243, 'max_depth': 18}. Best is trial 0 with value: 0.9934640522875817.
[I 2026-04-02 02:37:51,611] Trial 4 finished with value: 0.9607843137254902 and parameters: {'n_estimators': 207, 'max_depth': 10}. Best is trial 0 with value: 0.9934640522875817.
[I 2026-04-02 02:38:02,480] Trial 5 finished with value: 0.9934640522875817 and parameters: {'n_estimators': 416, 'max_depth': 23}. Best is trial 0 with value: 0.9934640522875817.
[I 2026-04-02 02:38:11,246] Trial 6 finished with value: 0.9934640522875817 and parameters: {'n_estimators': 315, 'max_depth': 29}. Best is trial 0 with value: 0.9934640522875817.
[I 2026-04-02 02:38:17,099] Trial 7 finished with value: 0.9847494553376906 and parameters: {'n_estimators': 232, 'max_depth': 11}. Best is trial 0 with value: 0.9934640522875817.
[I 2026-04-02 02:38:29,240] Trial 8 finished with value: 0.9934640522875817 and parameters: {'n_estimators': 440, 'max_depth': 40}. Best is trial 0 with value: 0.9934640522875817.
[I 2026-04-02 02:38:39,187] Trial 9 finished with value: 0.9934640522875817 and parameters: {'n_estimators': 445, 'max_depth': 31}. Best is trial 0 with value: 0.9934640522875817.

In [108]:
best_n_estimators = study.best_params['n_estimators']
best_max_depth = study.best_params['max_depth']

best_model = RandomForestClassifier(n_estimators=best_n_estimators, max_depth=best_max_depth)
rfe = RFE(estimator=best_model, n_features_to_select=10)
rfe.fit(X_train_1, y_train_1)

rfe.support_

array([ True, False, False, False,  True, False,  True, False,  True,
        True, False,  True, False, False,  True, False,  True,  True,
        True])

In [109]:
list(zip(numerical_cols,rfe.support_))
selected_features=[feature for feature, selected in zip(numerical_cols,rfe.support_) if selected]
print(selected_features)

['gender', 'tenure', 'MultipleLines', 'OnlineSecurity', 'OnlineBackup', 'TechSupport', 'Contract', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges']

In [110]:
import pickle
with open('rfe.pickle',"wb") as f:
  pickle.dump(rfe,f)

In [111]:
%pip install tensorflow 
import tensorflow as tf
from tensorflow.keras import layers,models

Requirement already satisfied: tensorflow in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\asus\appdata\roaming\python\python313\site-packages (from tensorflow) (26.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (7.34.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.33.1)
Requirement already satisfied: setuptools in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (82.0.1)
Requirement already satisfied: six>=1.12.0 in c:\users\asus\appdata\roaming\python\python313\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (1.80.0)
Requirement already satisfied: keras>=3.12.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.4.4)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.2.25)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.46.3)
Requirement already satisfied: rich in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from keras>=3.12.0->tensorflow) (14.3.3)
Requirement already satisfied: namex in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\asus\appdata\roaming\python\python313\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [112]:
def create_ann_model():
  model=models.Sequential([
      layers.Dense(64,activation='relu',input_shape=(10,)),
      layers.Dense(32,activation='relu'),
      layers.Dense(16,activation='relu'),
      layers.Dense(8,activation='relu'),
      layers.Dense(1,activation='sigmoid')
  ])
  return model

In [113]:
ann_model=create_ann_model()
ann_model.summary()

c:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_5 (Dense)                 │ (None, 64)             │           704 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,457 (13.50 KB)

 Trainable params: 3,457 (13.50 KB)

 Non-trainable params: 0 (0.00 B)

In [114]:
ann_model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [115]:
X_train_rfe = rfe.transform(X_train_1)
ann_model.fit(X_train_rfe,y_train_1,epochs=32,batch_size=32,validation_split=0.25)

Epoch 1/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7980 - loss: 1.7320 - val_accuracy: 0.4433 - val_loss: 1.5812
Epoch 2/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7922 - loss: 0.9404 - val_accuracy: 0.8674 - val_loss: 0.3727
Epoch 3/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8213 - loss: 0.7498 - val_accuracy: 0.8709 - val_loss: 0.5379
Epoch 4/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8126 - loss: 0.8513 - val_accuracy: 0.8761 - val_loss: 0.4737
Epoch 5/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8370 - loss: 0.4102 - val_accuracy: 0.8656 - val_loss: 0.3709
Epoch 6/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8324 - loss: 0.8115 - val_accuracy: 0.4520 - val_loss: 4.3719
Epoch 7/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8132 - loss: 0.8062 - val_accuracy: 0.8778 - val_loss: 0.5210
Epoch 8/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8236 - loss: 0.4974 - val_accuracy: 0.8639 - val_loss: 0.3628
Epoch 9/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8207 - loss: 0.5653 - val_accuracy: 0.6457 - val_loss: 0.7119
Epoch 10/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8300 - loss: 0.4973 - val_accuracy: 0.8778 - val_loss: 0.3421
Epoch 11/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8225 - loss: 0.5081 - val_accuracy: 0.8761 - val_loss: 0.4090
Epoch 12/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8236 - loss: 0.7010 - val_accuracy: 0.8848 - val_loss: 0.4269
Epoch 13/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8108 - loss: 0.9873 - val_accuracy: 0.8709 - val_loss: 0.5349
Epoch 14/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8114 - loss: 0.5210 - val_accuracy: 0.8674 - val_loss: 0.4149
Epoch 15/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8271 - loss: 0.6299 - val_accuracy: 0.8691 - val_loss: 0.4751
Epoch 16/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8161 - loss: 0.6681 - val_accuracy: 0.8743 - val_loss: 0.5001
Epoch 17/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8178 - loss: 0.6377 - val_accuracy: 0.8674 - val_loss: 0.7694
Epoch 18/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8068 - loss: 0.6776 - val_accuracy: 0.8691 - val_loss: 0.4574
Epoch 19/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8347 - loss: 0.5213 - val_accuracy: 0.8831 - val_loss: 0.3094
Epoch 20/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8335 - loss: 0.6224 - val_accuracy: 0.8743 - val_loss: 0.5155
Epoch 21/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8300 - loss: 0.4482 - val_accuracy: 0.8709 - val_loss: 0.3224
Epoch 22/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8184 - loss: 0.6161 - val_accuracy: 0.8691 - val_loss: 0.4173
Epoch 23/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8289 - loss: 0.4846 - val_accuracy: 0.8691 - val_loss: 0.3211
Epoch 24/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8446 - loss: 0.4157 - val_accuracy: 0.7557 - val_loss: 0.4771
Epoch 25/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8242 - loss: 0.5187 - val_accuracy: 0.8656 - val_loss: 0.3688
Epoch 26/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8271 - loss: 0.4949 - val_accuracy: 0.8639 - val_loss: 0.4448
Epoch 27/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8225 - loss: 0.5216 - val_accuracy: 0.8743 - val_loss: 0.3430
Epoch 28/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8324 - loss: 0.4775 - val_accuracy: 0.8761 - val_loss: 0.3331
Epoch 29/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8347 - loss: 0.4060 - val_accuracy: 0.8674 - val_loss: 0.5014
Epoch 30/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8196 - loss: 0.5330 - val_accuracy: 0.8796 - val_loss: 0.3070
Epoch 31/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8469 - loss: 0.3719 - val_accuracy: 0.8604 - val_loss: 0.3487
Epoch 32/32
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8393 - loss: 0.4270 - val_accuracy: 0.8778 - val_loss: 0.3060

In [124]:
X_test_rfe=rfe.transform(X_test)
predictions=ann_model.predict(X_test_rfe)
print(predictions.min())

18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
0.34814128

c:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(

In [125]:
y_true = y_test
y_pred = (predictions > 0.45).astype(int)
cm = tf.math.confusion_matrix(labels=y_true, predictions=y_pred)
print(cm)

tf.Tensor(
[[303 176]
 [ 20  74]], shape=(2, 2), dtype=int32)

In [126]:
ann_model.evaluate(X_test_rfe,y_test)

18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7923 - loss: 0.6025

[0.6024852991104126, 0.7923211455345154]

In [128]:

with open('rfe.pickle', 'rb') as file:
    data = pickle.load(file)
print(data)

RFE(estimator=RandomForestClassifier(max_depth=26, n_estimators=169),
    n_features_to_select=10)